# Generated by Django 4.2.11 on 2024-04-13 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('booking_portal', '0020_alter_faculty_customuser_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('R2', 'Waiting for lab assistant approval.'), ('R3', 'Approved'), ('R4', 'Rejected'), ('R5', 'Cancelled')], max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking_portal.faculty')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking_portal.instrument')),
                ('lab_assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='booking_portal.labassistant')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_portal.slot')),
            ],
        ),
    ]
