# Generated by Django 4.2.11 on 2024-04-13 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('booking_portal', '0021_facultyrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='user_name',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='sup_dept',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='sup_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_portal.faculty'),
        ),
    ]
