# Generated by Django 4.2.9 on 2024-05-26 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_portal', '0021_vsm'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPR_ESR',
            fields=[
                ('userremark_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='booking_portal.userremark')),
                ('userdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking_portal.userdetail')),
                ('sample_code', models.CharField(max_length=75)),
                ('sample_nature', models.CharField(choices=[('Liquid', 'Liquid'), ('Powder', 'Powder')], max_length=10)),
                ('field', models.CharField(max_length=75)),
                ('temperature_series', models.CharField(max_length=75)),
            ],
            options={
                'verbose_name': 'EPR/ESR',
                'verbose_name_plural': 'EPR/ESR',
            },
            bases=('booking_portal.userdetail', 'booking_portal.userremark'),
        ),
    ]
