# Generated by Django 4.2.9 on 2024-05-26 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_portal', '0023_gpc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHNS',
            fields=[
                ('userremark_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='booking_portal.userremark')),
                ('userdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking_portal.userdetail')),
                ('sample_code', models.CharField(max_length=75)),
                ('sample_nature', models.CharField(choices=[('Liquid', 'Liquid'), ('Powder', 'Powder')], max_length=10)),
                ('parameters', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'CHNS',
                'verbose_name_plural': 'CHNS',
            },
            bases=('booking_portal.userdetail', 'booking_portal.userremark'),
        ),
    ]
