# Generated by Django 4.2.9 on 2024-06-03 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_portal", "0024_chns"),
    ]

    operations = [
        migrations.CreateModel(
            name="RT_PCR",
            fields=[
                (
                    "userremark_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="booking_portal.userremark",
                    ),
                ),
                (
                    "userdetail_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="booking_portal.userdetail",
                    ),
                ),
                ("sample_type", models.CharField(max_length=75)),
                ("slot_duration", models.CharField(max_length=75)),
                ("fluorophore", models.CharField(max_length=75)),
                ("strips_plate", models.CharField(max_length=75)),
            ],
            options={
                "verbose_name": "RT-PCR",
                "verbose_name_plural": "RT-PCR",
            },
            bases=("booking_portal.userdetail", "booking_portal.userremark"),
        ),
    ]
