# Generated by Django 4.2.9 on 2024-06-04 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_portal', '0025_rt_pcr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantachrome',
            fields=[
                ('userremark_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='booking_portal.userremark')),
                ('userdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking_portal.userdetail')),
                ('sample_code', models.CharField(max_length=75)),
                ('pretreatment_conditions', models.CharField(max_length=200)),
                ('precautions', models.CharField(max_length=200)),
                ('adsorption', models.CharField(max_length=75)),
                ('surface_area_pore_size', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Quantachrome',
                'verbose_name_plural': 'Quantachrome',
            },
            bases=('booking_portal.userdetail', 'booking_portal.userremark'),
        ),
    ]
