# Generated by Django 4.2.9 on 2024-06-04 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_portal', '0026_quantachrome'),
    ]

    operations = [
        migrations.CreateModel(
            name='DLS',
            fields=[
                ('userremark_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='booking_portal.userremark')),
                ('userdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking_portal.userdetail')),
                ('sample_codes', models.CharField(max_length=75)),
                ('slot_duration', models.CharField(max_length=75)),
                ('cuvettes', models.CharField(choices=[('Disposable', 'Disposable'), ('Glass', 'Glass'), ('Quartz', 'Quartz'), ('Omega', 'Omega'), ('Univette', 'Univette')], max_length=10)),
                ('solvent', models.CharField(max_length=75)),
                ('additional_info', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'DLS',
                'verbose_name_plural': 'DLS',
            },
            bases=('booking_portal.userdetail', 'booking_portal.userremark'),
        ),
    ]
