# Generated by Django 4.2.9 on 2024-06-05 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_portal", "0029_contactangle"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalPolarimeter",
            fields=[
                (
                    "userremark_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="booking_portal.userremark",
                    ),
                ),
                (
                    "userdetail_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="booking_portal.userdetail",
                    ),
                ),
                ("sample_codes", models.CharField(max_length=75)),
                ("slot_duration", models.CharField(max_length=75)),
                ("filters_used", models.CharField(max_length=75)),
                ("measurement_type", models.CharField(max_length=75)),
                ("solvent", models.CharField(max_length=75)),
                ("cuvette_path_length", models.CharField(max_length=300)),
                ("additional_info", models.CharField(max_length=300)),
            ],
            options={
                "verbose_name": "Digital Polarimeter",
                "verbose_name_plural": "Digital Polarimeter",
            },
            bases=("booking_portal.userdetail", "booking_portal.userremark"),
        ),
    ]
