# Generated by Django 4.2.9 on 2024-06-08 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_portal', '0034_ultracentrifuge_alter_spectrafluorimeter_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.IntegerField()),
                ('hod_email', models.EmailField(max_length=100, unique=True, verbose_name='email address')),
                ('hod_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking_portal.department'),
        ),
    ]
