# Generated by Django 4.2.9 on 2024-06-08 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_portal', '0035_department_faculty_balance_alter_faculty_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'default_related_name': 'departments', 'verbose_name': 'Departments'},
        ),
        migrations.AddField(
            model_name='request',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='booking_portal.department'),
        ),
        migrations.AlterField(
            model_name='request',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='booking_portal.faculty'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('R1', 'Waiting for faculty approval.'), ('R2', 'Waiting for lab assistant approval.'), ('R6', 'Waiting for department approval.'), ('R3', 'Approved'), ('R4', 'Rejected'), ('R5', 'Cancelled')], max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='booking_portal.student'),
        ),
    ]
