# Generated by Django 4.2.9 on 2024-06-14 15:17

from booking_portal.models.user import CustomUser, Faculty, LabAssistant, Student
from django.db import migrations, models


def populate_roles(apps, schema):
    Student.objects.update(role=CustomUser.Role.STUDENT)
    Faculty.objects.update(role=CustomUser.Role.FACULTY)
    LabAssistant.objects.update(role=CustomUser.Role.LAB_ASSISTANT)
    CustomUser.objects.filter(is_staff=True).update(role=CustomUser.Role.STAFF)


class Migration(migrations.Migration):
    dependencies = [
        ("booking_portal", "0037_alter_userdetail_number_of_samples"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Student"),
                    ("FACULTY", "Faculty"),
                    ("LAB_ASSISTANT", "Lab Assistant"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.RunPython(populate_roles),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Student"),
                    ("FACULTY", "Faculty"),
                    ("LAB_ASSISTANT", "Lab Assistant"),
                ],
                max_length=50,
            ),
        ),
    ]
