# Generated by Django 4.2.9 on 2024-06-14 15:17

from django.db import migrations, models


def populate_roles(apps, schema):
    # Use the historical models: the live ones have drifted since this migration
    # was written (the STAFF role no longer exists, and staff users get their
    # role from 0072_alter_customuser_role).
    Student = apps.get_model("booking_portal", "Student")
    Faculty = apps.get_model("booking_portal", "Faculty")
    LabAssistant = apps.get_model("booking_portal", "LabAssistant")

    Student.objects.update(role="STUDENT")
    Faculty.objects.update(role="FACULTY")
    LabAssistant.objects.update(role="LAB_ASSISTANT")


class Migration(migrations.Migration):
    dependencies = [
        ("booking_portal", "0037_alter_userdetail_number_of_samples"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Student"),
                    ("FACULTY", "Faculty"),
                    ("LAB_ASSISTANT", "Lab Assistant"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.RunPython(populate_roles),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Student"),
                    ("FACULTY", "Faculty"),
                    ("LAB_ASSISTANT", "Lab Assistant"),
                ],
                max_length=50,
            ),
        ),
    ]
