# Generated by Django 4.2.9 on 2024-06-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_portal", "0041_alter_faculty_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="balance",
            field=models.IntegerField(default=0),
        ),
    ]
