# Generated by Django 4.2.9 on 2024-06-15 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("booking_portal", "0043_request_needs_department_approval_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Request",
            new_name="StudentRequest",
        ),
    ]
