# Generated by Django 4.2.9 on 2024-06-15 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('booking_portal', '0045_facultyrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='user_name',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
