# Generated by Django 4.2.9 on 2024-06-15 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_portal', '0046_remove_userdetail_user_name_userdetail_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='sup_dept',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='sup_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_portal.faculty'),
        ),
    ]
