# Generated by Django 4.2.9 on 2024-06-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_portal", "0048_balancetopuplog"),
    ]

    operations = [
        migrations.AddField(
            model_name="userremark",
            name="department_remarks",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
