# Generated by Django 4.2.9 on 2024-06-28 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_portal", "0049_userremark_department_remarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balancetopuplog",
            name="top_up_amount",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
