# Generated by Django 4.2.9 on 2024-07-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_portal', '0057_facultyrequest_additional_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='mode_time_in_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
