# Generated by Django 4.2.9 on 2024-08-10 13:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_portal', '0060_remove_modepricingrules_choices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreezeDryer',
            fields=[
                ('userremark_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='booking_portal.userremark')),
                ('userdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking_portal.userdetail')),
                ('sample_code', models.CharField(max_length=75)),
                ('solvent', models.CharField(max_length=75)),
                ('freezing_point', models.CharField(max_length=75)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Freeze Dryer',
                'verbose_name_plural': 'Freeze Dryer',
            },
            bases=('booking_portal.userdetail', 'booking_portal.userremark'),
        ),
    ]
