# Generated by Django 4.2.9 on 2024-09-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_portal', '0062_tubularmufflefurnace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modepricingrules',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
