# Generated by Django 4.2.9 on 2024-12-18 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_portal", "0064_alter_customuser_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="AFM",
            fields=[
                (
                    "userremark_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="booking_portal.userremark",
                    ),
                ),
                (
                    "userdetail_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="booking_portal.userdetail",
                    ),
                ),
                ("sample_code", models.CharField(max_length=75)),
                (
                    "sample_nature",
                    models.CharField(choices=[("Film", "Film")], max_length=10),
                ),
                (
                    "imaging_mode",
                    models.CharField(
                        choices=[
                            ("Static Force", "Static Force"),
                            ("Dynamic Force", "Dynamic Force"),
                            ("Phase Contrast", "Phase Contrast"),
                            ("Lateral Force", "Lateral Force"),
                            ("Standard Spectroscopy", "Standard Spectroscopy"),
                            ("Force Modulation", "Force Modulation"),
                            ("Standard Lithography", "Standard Lithography"),
                            ("Standard Conductive AFM", "Standard Conductive AFM"),
                            ("EFM", "EFM"),
                            ("MFM", "MFM"),
                            ("Liquid Cell Imaging", "Liquid Cell Imaging"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "AFM",
                "verbose_name_plural": "AFM",
            },
            bases=("booking_portal.userdetail", "booking_portal.userremark"),
        ),
    ]
