# Generated by Django 4.2.9 on 2025-01-22 08:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_portal", "0065_afm"),
    ]

    operations = [
        migrations.CreateModel(
            name="ICPMS",
            fields=[
                (
                    "userremark_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="booking_portal.userremark",
                    ),
                ),
                (
                    "userdetail_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="booking_portal.userdetail",
                    ),
                ),
                ("sample_code", models.CharField(max_length=75)),
                ("sample_state", models.CharField(max_length=75)),
                (
                    "digestion_carried_out",
                    models.CharField(
                        blank=True,
                        choices=[("Yes", "Yes"), ("No", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "target_elements_concentration",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(1000),
                            django.core.validators.MinValueValidator(1),
                        ]
                    ),
                ),
                (
                    "sample_filtered",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")], max_length=3
                    ),
                ),
                (
                    "calibration_solution_concentration",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(1000),
                            django.core.validators.MinValueValidator(1),
                        ]
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("Standard", "Standard"),
                            ("Literature", "Literature"),
                        ],
                        max_length=75,
                    ),
                ),
            ],
            options={
                "verbose_name": "ICP-MS",
                "verbose_name_plural": "ICP-MS",
            },
            bases=("booking_portal.userdetail", "booking_portal.userremark"),
        ),
    ]
