# Generated by Django 4.2.9 on 2025-01-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_portal", "0066_icpms"),
    ]

    operations = [
        migrations.AddField(
            model_name="icpms",
            name="elements",
            field=models.CharField(default=None, max_length=75),
            preserve_default=False,
        ),
    ]
