# Generated by Django 4.2.20 on 2025-09-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "booking_portal",
            "0068_remove_icpms_calibration_solution_concentration_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="slot",
            index=models.Index(fields=["status", "date"], name="slot_status_date_idx"),
        ),
    ]
