# Generated by Django 4.2.20 on 2026-01-19 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_portal", "0070_emailmodel_email_type_emailmodel_email_type_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfocalRamanSpectrometer",
            fields=[
                (
                    "userremark_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="booking_portal.userremark",
                    ),
                ),
                (
                    "userdetail_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="booking_portal.userdetail",
                    ),
                ),
                ("sample_code", models.CharField(max_length=75)),
                (
                    "sample_nature",
                    models.CharField(
                        choices=[("Powder", "Powder"), ("Film", "Film")], max_length=10
                    ),
                ),
                ("scan_range_start", models.IntegerField()),
                ("scan_range_end", models.IntegerField()),
                ("wavelength", models.IntegerField()),
            ],
            options={
                "verbose_name": "Confocal Raman Spectrometer",
                "verbose_name_plural": "Confocal Raman Spectrometer",
            },
            bases=("booking_portal.userdetail", "booking_portal.userremark"),
        ),
    ]
