# Generated by Django 4.2.20 on 2026-05-07 18:18

from django.db import migrations, models


def migrate_staff_role(apps, schema_editor):
    CustomUser = apps.get_model("booking_portal", "CustomUser")
    CustomUser.objects.filter(role="STAFF").update(role="PORTAL_ADMIN")


class Migration(migrations.Migration):
    dependencies = [
        ("booking_portal", "0071_confocalramanspectrometer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("PORTAL_ADMIN", "Portal Admin"),
                    ("STUDENT", "Student"),
                    ("FACULTY", "Faculty"),
                    ("LAB_ASSISTANT", "Lab Assistant"),
                    ("DEPARTMENT", "Department"),
                ],
                max_length=50,
            ),
        ),
        migrations.RunPython(migrate_staff_role, migrations.RunPython.noop),
    ]
