# Generated by Django 4.2.30 on 2026-07-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking_portal", "0072_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="additionalpricingrules",
            options={"verbose_name_plural": "Additional pricing rules"},
        ),
        migrations.AlterModelOptions(
            name="modepricingrules",
            options={"verbose_name_plural": "Mode pricing rules"},
        ),
        migrations.AlterField(
            model_name="emailmodel",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("faculty_approval", "Waiting for Faculty Approval"),
                    ("pending_booking", "Pending Lab Booking Request"),
                    ("department_approval", "Waiting for Department Approval"),
                    ("lab_assistant_approval", "Waiting for Lab Assistant Approval"),
                    ("booking_approved", "Lab Booking Approved"),
                    ("booking_rejected", "Lab Booking Rejected"),
                    ("booking_cancelled", "Lab Booking Cancelled"),
                    ("new_announcement", "New Announcement Created on CIF Portal"),
                    ("welcome", "Welcome to OnlineCIF!"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="Type of email for categorization and filtering",
                max_length=50,
            ),
        ),
    ]
