# Generated by Django 4.2.30 on 2026-09-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking_portal", "0073_alter_additionalpricingrules_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailmodel",
            name="bcc",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Comma-separated BCC recipients of a batched email",
            ),
        ),
        migrations.AlterField(
            model_name="emailmodel",
            name="receiver",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
