# Generated by Django 4.2.30 on 2026-09-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking_portal", "0074_emailmodel_bcc_alter_emailmodel_receiver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailmodel",
            name="subject",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
