from .aas import AASForm
from .afm import AFMForm
from .bdfacs import BDFACSForm
from .bet import BETForm
from .cdspectrophotometer import CDSpectrophotometerForm
from .chns import CHNSForm
from .contact_angle import ContactAngleForm
from .digital_polarimeter import DigitalPolarimeterForm
from .dls import DLSForm
from .dsc import DSCForm
from .edxrf import EDXRFForm
from .epr_esr import EPR_ESRForm
from .fesem import FESEMForm
from .fluorolog3 import Fluorolog3Form
from .fluoromax import FluoromaxForm
from .freezedryer import FreezeDryerForm
from .ftir import FTIRForm
from .gc import GCForm
from .gpc import GPCForm
from .hplc import HPLCForm
from .hplc_fd import HPLC_FDForm
from .lcms import LCMSForm
from .lscm import LSCMForm
from .mufflefurnace1 import MuffleFurnace1Form
from .mufflefurnace2 import MuffleFurnace2Form
from .mufflefurnace3 import MuffleFurnace3Form
from .nmr import NMRForm
from .pxrd import PXRDForm
from .quantachrome import QuantachromeForm
from .rheometer import RheometerForm
from .rt_pcr import RT_PCRForm
from .saxs_waxs import SAXSWAXSForm
from .scxrd import SCXRDForm
from .spectrafluorimeter import SpectraFluorimeterForm
from .tcspc import TCSPCForm
from .tga import TGAForm
from .tubularfurnace import TubularFurnaceForm
from .ultracentrifuge import UltracentrifugeForm
from .utm import UTMForm
from .uvspectrophotometer import UVSpectrophotometerForm
from .vsm import VSMForm
from .xps import XPSForm
