from .aas import AASForm
from .bet import BETForm
from .cdspectrophotometer import CDSpectrophotometerForm
from .dsc import DSCForm
from .edxrf import EDXRFForm
from .fesem import FESEMForm
from .ftir import FTIRForm
from .gc import GCForm
from .hplc import HPLCForm
from .hplc_fd import HPLC_FDForm
from .lcms import LCMSForm
from .lscm import LSCMForm
from .nmr import NMRForm
from .pxrd import PXRDForm
from .rheometer import RheometerForm
from .saxs_waxs import SAXSWAXSForm
from .scxrd import SCXRDForm
from .tcspc import TCSPCForm
from .tga import TGAForm
from .uvspectrophotometer import UVSpectrophotometerForm
from .xps import XPSForm
from .utm import UTMForm
from .vsm import VSMForm
from .epr_esr import EPR_ESRForm
from .gpc import GPCForm
from .chns import CHNSForm
from .rt_pcr import RT_PCRForm
from .quantachrome import QuantachromeForm
from .dls import DLSForm
from .bdfacs import BDFACSForm
from .contact_angle import ContactAngleForm
from .digital_polarimeter import DigitalPolarimeterForm
from .fluorolog3 import Fluorolog3Form
from .fluoromax import Fluoromax
from .spectrafluorimeter import SpectraFluorimeterForm
