name: Deploy onlineCAL

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        env:
          POETRY_VIRTUALENVS_IN_PROJECT: true
        run: |
            cd /home/ubuntu/onlineCAL/server

            git pull origin master

            source $(poetry env info --path)/bin/activate
            poetry install --no-root
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput

            sudo supervisorctl restart onlineCAL
